config/routes.rb
Rails.application.routes.draw do
  
  namespace :public do
    get 'orders/new'
    get 'orders/show'
    get 'orders/edit'
  end
  namespace :admin do
    get 'order_items/show'
    get 'order_items/index'
  end
  namespace :public do
    get 'order_items/show'
    get 'order_items/index'
  end
  namespace :public do
    get 'items/show'
    get 'items/index'
  end
  scope module: :public do
  root to: "homes#top"
  end 

  namespace :admin do
    resources :customers
    resources :genres
    resources :items
    # get 'customers/show'
    # get 'customers/index'
    # get 'customers/edit'
  end
  
  
  namespace :public do
    resources :customers
    get 'homes/about'
    # get 'customers/show'
    # get 'customers/edit'
  end
  
    # get 'genres/edit'
    # get 'genres/index'
    # get 'genres/new'
  
    # get 'items/edit'
    # get 'items/index'
    # get 'items/new'
    # get 'items/show'
  
  devise_for :customers,skip: [:passwords],controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin,skip:[:registrations, :passwords],controllers: {
  sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.all
  end

  def edit
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def new
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new
    @genre.user_id = current_admin
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end 

  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end 


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    # @item.user_id = current_user.id
    if @item.save
      redirect_to admin_items_path
    else
      render :new
    end
  end

  def index
    @items =Item.all
  end

  def show
    @item = Item.find(params[:id])  
  end
  
  def edit
  end

end

  private
  def list_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image)  
  end

app/controllers/admin/order_items_controller.rb
class Admin::OrderItemsController < ApplicationController
  def show
  end

  def index
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h1>Admin::Customers#edit</h1>
<p>Find me in app/views/admin/customers/edit.html.erb</p>

app/views/admin/customers/index.html.erb
<h3>会員一覧</h3>

<table class="table">
  <thead>
    <tr>
      <th scope="col">会員ID</th>
      <th scope="col">氏名</th>
      <th scope="col">メールアドレス</th>
      <th scope="col">ステータス</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @customers.each do |customer| %>
      <td><%= customers.id %></td>
      <td><%= customers.last_name %><%= customers.first_name %></td>
      <td><%= customers.email %></td>
      <td><%= customers.is_deleted %></td>
    </tr>
    
  </tbody>
</table>

app/views/admin/customers/show.html.erb
      <h2><%= customers.last_name %><%= customers.first_name %>さんの会員詳細</h2>
      
      
      <table class="table table-hover table-inverse">

        <th>会員ID</th>
        <td><%= @customer.id %></td>
        <th>氏名</th>
        <td><%= @customer.last_name %><%= @customer.first_name %></td>
        <th>フリガナ</th>
        <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
        <th>郵便番号</th>
        <td><%= @customer.postal_code %></td>
        <th>住所</th>
        <td><%= @customer.address %></td>
        <th>電話番号</th>
        <td><%= @customer.telephone_number %></td>
        <th>メールアドレス</th>
        <td><%= @customer.email %></td>
        <th>会員ステータス</th>
        <td><%= @customer.ie_deleted %></td>
      </table>

app/views/admin/genres/edit.html.erb
<%= form_with model:genre  do |f| %>
      <h2 class="mt-3">ジャンル編集</h2>
        <label for="name">ジャンル名</label>
          <%= f.text_field :name, class: "form-control genre_name" %>
          <%= f.submit '変更を保存', class: "btn btn-success" %>
<% end %>

app/views/admin/genres/index.html.erb
<%= form_with model: @genre, url:admin_genres_path do |f| %>
      <h2 class="mt-3">ジャンル一覧・追加</h2>
        <h6>ジャンル名</h6>
          <%= f.text_field :name, class: "form-control genre_name" %>
          <%= f.submit '新規登録', class: "btn btn-success" %>
<% end %>


  
<table class="table">
  <thead>
    <tr>
      <th scope="col">ジャンル名</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <td><%= link_to "編集する",  edit_admin_genre_path, class:"btn btn-sm btn-success" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/genres/new.html.erb
<h1>Admin::Genres#new</h1>
<p>Find me in app/views/admin/genres/new.html.erb</p>

app/views/admin/items/edit.html.erb
<h1>Admin::Items#edit</h1>
<p>Find me in app/views/admin/items/edit.html.erb</p>

app/views/admin/items/index.html.erb
<h3>商品一覧</h3>

<table class="table">
  <thead>
    <tr>
      <th scope="col">商品ID</th>
      <th scope="col">商品名</th>
      <th scope="col">税抜価格</th>
      <th scope="col">ジャンル</th>
      <th scope="col">ステータス</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @items.each do |item| %>
      <td><%= items.id %></td>
      <td><%= items.name %></td>
      <td><%= items.price %></td>
      <td><%= items.genre_id %></td>
      <td><%= items.is_active %></td>
    </tr>
  </tbody>
</table>

app/views/admin/items/new.html.erb
<div class="container">
  <!--<div class="row no-gutters">-->
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">商品新規登録</h5>
      <div class="form-body p-4">
        <% if @item.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @item.errors.count %>件のエラーが発生しました
            </h6>
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        
        
        <%= form_with model: @items do |f| %>
          <%= f.file_field :image, accept: "image/*"%>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
            </div>
            <h5>商品名</h5><%= f.text_field :name, class:"form-control", placeholder:"商品名" %>
          </div>
          <h5>商品説明</h5><%= f.text_area :introduction, class:"form-control", rows:"3", placeholder:"商品説明" %>
            <h5>ジャンル</h5>
            <%= f.select :amount, *[1..10], placeholder:"--選択してください--" %> 
            <h5>税抜き価格</h5>
            <%= f.text_field :price, class:"form-control", placeholder:"1000" %>
            
          
          <%= f.submit '新規登録', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
    <div class="col-md-8 offset-md-1">
      <h2>商品詳細</h2>
      <table class="table table-hover table-inverse">
        <th>商品名</th>
        <td><%= item.name %></td>
        <th>商品説明</th>
        <td><%= item.introduction %></td>
        <th>ジャンル</th>
        <td><%= item.genre %></td>
        <th>税込価格<br>税抜き価格</th>
        <td><%= item.price %></td>
        <th>販売ステータス</th>
        <td><%= item.is_active %></td>
      </table>
    </div>
        
        
        <% if @item.user == admin_user %>
              <%= link_to "編集する", edit_admin_item_path, class:"btn btn-sm btn-success" %>
        <% end %>

app/views/admin/order_items/index.html.erb
<h1>Admin::OrderItems#index</h1>
<p>Find me in app/views/admin/order_items/index.html.erb</p>

app/views/admin/order_items/show.html.erb
<h1>Admin::OrderItems#show</h1>
<p>Find me in app/views/admin/order_items/show.html.erb</p>